import { Package, City, Car } from '../types';

export const fallbackProvinces = [
  { id: 'prov-1', name: 'Sumatera Utara', description: 'Danau Toba & Budaya Batak', image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd' },
];

export const fallbackCities: City[] = [
  { id: 'city-1', provinceId: 'prov-1', name: 'Danau Toba', description: 'Danau vulkanik terbesar di dunia' },
  { id: 'city-2', provinceId: 'prov-1', name: 'Samosir', description: 'Pulau di tengah Danau Toba' },
  { id: 'city-3', provinceId: 'prov-1', name: 'Berastagi', description: 'Kota wisata di kaki Gunung Sinabung' },
  { id: 'city-4', provinceId: 'prov-1', name: 'Tangkahan', description: 'Surga tersembunyi di Langkat' },
  { id: 'city-5', provinceId: 'prov-1', name: 'Bukit Lawang', description: 'Pintu masuk Taman Nasional Gunung Leuser' },
  { id: 'city-6', provinceId: 'prov-1', name: 'Medan', description: 'Ibukota Sumatera Utara' },
];

export const fallbackPackages: any[] = [
  {
    id: 'pkg-1',
    name: 'Pesona Danau Toba & Budaya Batak',
    slug: 'pesona-danau-toba-budaya-batak',
    description: 'Jelajahi keindahan Danau Toba yang memukau dan rasakan kekayaan budaya Batak yang autentik. Nikmati pemandangan danau vulkanik terbesar di dunia dari berbagai sudut pandang.',
    price: 3500000,
    duration: '4 Hari 3 Malam',
    cityId: 'city-1',
    location: 'Danau Toba',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&q=80&w=800',
    includes: ['Hotel Bintang 3 di Parapat', 'Makan 3x Sehari (Masakan Batak)', 'Transport AC Medan–Toba PP', 'Guide Lokal Berpengalaman', 'Tiket Masuk Destinasi', 'Naik Kapal ke Samosir'],
    excludes: ['Tiket Pesawat ke Medan', 'Pengeluaran Pribadi', 'Tip Guide', 'Oleh-oleh'],
    images: ['https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
  },
  {
    id: 'pkg-2',
    name: 'Eksplorasi Pulau Samosir',
    slug: 'eksplorasi-pulau-samosir',
    description: 'Kunjungi Pulau Samosir yang eksotis di tengah Danau Toba. Temukan rumah adat Batak, patung Sigale-gale, dan keindahan alam yang tiada duanya.',
    price: 2800000,
    duration: '3 Hari 2 Malam',
    cityId: 'city-2',
    location: 'Samosir',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=800',
    includes: ['Penginapan Tepi Danau Toba', 'Makan 2x Sehari', 'Kapal Feri Ajibata–Tomok', 'Guide Lokal Samosir', 'Kunjungan Desa Adat Batak'],
    excludes: ['Tiket Pesawat ke Medan', 'Pengeluaran Pribadi', 'Souvenir'],
    images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
  },
  {
    id: 'pkg-3',
    name: 'Petualangan Berastagi & Gunung Sinabung',
    slug: 'petualangan-berastagi-gunung-sinabung',
    description: 'Rasakan kesegaran udara pegunungan Berastagi sambil menikmati pemandangan Gunung Sinabung yang megah. Kunjungi pasar buah dan sayur yang terkenal.',
    price: 2200000,
    duration: '2 Hari 1 Malam',
    cityId: 'city-3',
    location: 'Berastagi',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800',
    includes: ['Hotel di Berastagi', 'Makan 2x Sehari', 'Transport AC', 'Guide Lokal', 'Kunjungan Pasar Buah Berastagi'],
    excludes: ['Tiket Pesawat ke Medan', 'Pengeluaran Pribadi', 'Oleh-oleh'],
    images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
  },
  {
    id: 'pkg-4',
    name: 'Ekowisata Tangkahan & Gajah Sumatera',
    slug: 'ekowisata-tangkahan-gajah-sumatera',
    description: 'Pengalaman tak terlupakan berinteraksi dengan gajah Sumatera jinak di Tangkahan. Mandi bersama gajah di sungai jernih dan jelajahi hutan tropis yang masih alami.',
    price: 3200000,
    duration: '3 Hari 2 Malam',
    cityId: 'city-4',
    location: 'Tangkahan',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=800',
    includes: ['Penginapan Eco Lodge Tangkahan', 'Makan 3x Sehari', 'Aktivitas Mandi Gajah', 'Guide Ranger TNGL', 'Trekking Hutan Tropis'],
    excludes: ['Tiket Pesawat ke Medan', 'Pengeluaran Pribadi', 'Tip Ranger'],
    images: ['https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
  },
  {
    id: 'pkg-5',
    name: 'Trekking Bukit Lawang & Orangutan',
    slug: 'trekking-bukit-lawang-orangutan',
    description: 'Petualangan trekking di hutan hujan tropis Bukit Lawang untuk melihat orangutan Sumatera liar dalam habitat aslinya. Pengalaman yang akan selalu dikenang.',
    price: 2900000,
    duration: '3 Hari 2 Malam',
    cityId: 'city-5',
    location: 'Bukit Lawang',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=800',
    includes: ['Penginapan di Bukit Lawang', 'Makan 3x Sehari', 'Guide Trekking Bersertifikat', 'Perlengkapan Trekking', 'Kunjungan Pusat Rehabilitasi Orangutan'],
    excludes: ['Tiket Pesawat ke Medan', 'Pengeluaran Pribadi', 'Tip Guide'],
    images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=800'],
    status: 'active',
  },
];

export const fallbackCars: any[] = [
  { id: 'car-1', name: 'Toyota Avanza', type: 'MPV', pricePerDay: 450000, status: 'available', image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800', seats: 7, fuel: 'Bensin', transmission: 'Manual', rating: 4.8 },
  { id: 'car-2', name: 'Mitsubishi Pajero Sport', type: 'SUV', pricePerDay: 1200000, status: 'available', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800', seats: 7, fuel: 'Solar', transmission: 'Otomatis', rating: 4.9 },
  { id: 'car-3', name: 'Toyota Innova Reborn', type: 'MPV', pricePerDay: 750000, status: 'available', image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800', seats: 8, fuel: 'Solar', transmission: 'Manual', rating: 4.7 },
  { id: 'car-4', name: 'Honda CR-V', type: 'SUV', pricePerDay: 900000, status: 'available', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800', seats: 5, fuel: 'Bensin', transmission: 'Otomatis', rating: 4.8 },
  { id: 'car-5', name: 'Toyota Alphard', type: 'Luxury', pricePerDay: 2500000, status: 'available', image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800', seats: 7, fuel: 'Bensin', transmission: 'Otomatis', rating: 5.0 },
];
